name: DrBenchmark
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.7,<3.13
  - pip
  - transformers>=4.0,<=4.49  # to prevent future version breakage (cf. warning tokenizer arg) 
  - datasets>=2.21  # >2.21 for HF_HUB_OFFLINE
  - evaluate>=0.4.1
  - sentencepiece
  - tensorboardX
  - scikit-learn>1.4  # >1.4 for clister.root_mean_square_error
  - seqeval  # for metrics/seqeval.py
  - beautifulsoup4  # for E3C
  - lxml  # for E3C
  - pillow  # for DiaMED
  - sacremoses  # for flaubert
  - xmltodict
  - pyyaml
  - pip:
    - syntok>=1.4.4  # for PXCorpus
